#!/usr/bin/env php

<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application so it is ready to receive (HTTP) / (Console) requests
| from the environment.
|
*/

$application = require __DIR__ . '/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the command will be
| executed in this console and the response sent back to a terminal.
|
*/

$kernel = $application->make('Illuminate\Contracts\Console\Kernel');

exit($kernel->handle(new ArgvInput, new ConsoleOutput));